#define COMMENT 0
#define COMMENT_CREATIONDATE 0
#define COMMENT_CREATOR 1
#define COMMENT_ID 2
#define COMMENT_LENGTH 3
#define COMMENT_PLACE 4
#define COMMENT_REPLYOFCOMMENT 5
#define COMMENT_REPLYOFPOST 6
#define COMMENT_BROWSERUSED 7
#define COMMENT_CONTENT 8
#define COMMENT_LOCATIONIP 9

#define FORUM 1
#define FORUM_CREATIONDATE 0
#define FORUM_ID 1
#define FORUM_MODERATOR 2
#define FORUM_TITLE 3

#define ORGANISATION 2
#define ORGANISATION_ID 0
#define ORGANISATION_PLACE 1
#define ORGANISATION_NAME 2
#define ORGANISATION_TYPE 3
#define ORGANISATION_URL 4

#define PERSON 3
#define PERSON_BIRTHDAY 0
#define PERSON_CREATIONDATE 1
#define PERSON_ID 2
#define PERSON_PLACE 3
#define PERSON_BROWSERUSED 4
#define PERSON_EMAIL 5
#define PERSON_FIRSTNAME 6
#define PERSON_GENDER 7
#define PERSON_LASTNAME 8
#define PERSON_LOCATIONIP 9
#define PERSON_SPEAKS 10

#define PLACE 4
#define PLACE_ID 0
#define PLACE_ISPARTOF 1
#define PLACE_NAME 2
#define PLACE_TYPE 3
#define PLACE_URL 4

#define POST 5
#define POST_CONTAINER 0
#define POST_CREATIONDATE 1
#define POST_CREATOR 2
#define POST_ID 3
#define POST_LENGTH 4
#define POST_PLACE 5
#define POST_BROWSERUSED 6
#define POST_CONTENT 7
#define POST_IMAGEFILE 8
#define POST_LANGUAGE 9
#define POST_LOCATIONIP 10

#define TAG 6
#define TAG_HASTYPE 0
#define TAG_ID 1
#define TAG_NAME 2
#define TAG_URL 3

#define TAGCLASS 7
#define TAGCLASS_ID 0
#define TAGCLASS_ISSUBCLASSOF 1
#define TAGCLASS_NAME 2
#define TAGCLASS_URL 3

#define COMMENTHASCREATOR 0
#define COMMENTHASCREATOR_CREATIONDATE 0

#define COMMENTHASTAG 1

#define COMMENTISLOCATEDIN 2
#define COMMENTISLOCATEDIN_CREATIONDATE 0

#define REPLYOF 3
#define REPLYOF_CREATIONDATE 0

#define CONTAINEROF 4

#define HASMEMBER 5
#define HASMEMBER_FORUMID 0
#define HASMEMBER_JOINDATE 1
#define HASMEMBER_NUMPOSTS 2

#define HASMODERATOR 6

#define FORUMHASTAG 7

#define ORGANISATIONISLOCATEDIN 8

#define HASINTEREST 9

#define PERSONISLOCATEDIN 10

#define KNOWS 11
#define KNOWS_CREATIONDATE 0
#define KNOWS_WEIGHT 1

#define LIKES 12
#define LIKES_CREATIONDATE 0

#define STUDYAT 13
#define STUDYAT_CLASSYEAR 0

#define WORKAT 14
#define WORKAT_WORKFROM 0

#define ISPARTOF 15

#define POSTHASCREATOR 16
#define POSTHASCREATOR_CREATIONDATE 0

#define POSTHASTAG 17

#define POSTISLOCATEDIN 18
#define POSTISLOCATEDIN_CREATIONDATE 0

#define HASTYPE 19

#define ISSUBCLASSOF 20

